#!/usr/bin/env python3
"""Build inbox/adr-toc.md from raw/adr/ — one row per ADR of nats-architecture-and-design.

    python3 tools/triage-adrs.py

Reads the `| Metadata | Value |` header of every raw/adr/ADR-<n>.md (Date, Author, Status, Tags),
maps the ADR tags onto this wiki's `area` facet, flags the ones that explain observable server
behaviour, and preserves the `summary` column of an existing table so it can be re-run after
ingests. Registered in wiki.json under `tocs` — the viewer renders it as a filterable table.
"""
import os, re, glob, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, 'raw', 'adr')
OUT = os.path.join(ROOT, 'inbox', 'adr-toc.md')

# ADR tag -> this wiki's area facet values
AREA = {'jetstream': 'jetstream', 'kv': 'kv', 'objectstore': 'objectstore', 'security': 'security',
        'observability': 'monitoring', 'server': 'core', 'client': 'clients', 'spec': '', 'orbit': '',
        'refinement': '', 'deprecated': ''}
VERSION = re.compile(r'^\d+\.\d+$')


def meta(text):
    """The Date/Author/Status/Tags rows of the ADR's metadata table."""
    out = {}
    for k, v in re.findall(r'^\|\s*(Date|Author|Status|Tags)\s*\|\s*(.*?)\s*\|\s*$', text, re.M):
        out.setdefault(k.lower(), v.strip())
    return out


def previous_summaries():
    """Keep the `summary` cells (and any hand-set flags) of an existing table when re-running."""
    keep = {}
    if not os.path.exists(OUT):
        return keep
    for line in open(OUT, encoding='utf-8'):
        if not line.startswith('|'):
            continue
        c = [x.strip() for x in line.strip().strip('|').split('|')]
        if len(c) >= 8 and re.match(r'^\d+$', c[0]):
            keep[c[0]] = c[7]
    return keep


def main():
    keep = previous_summaries()
    rows = []
    for path in glob.glob(os.path.join(RAW, 'ADR-*.md')):
        name = os.path.basename(path)
        num = re.match(r'ADR-(\d+)\.md$', name)
        if not num:
            continue
        text = open(path, encoding='utf-8').read()
        m = meta(text)
        title = (re.search(r'^#\s+(.+)$', text, re.M) or re.match('', '')).group(1).strip() if re.search(r'^#\s+(.+)$', text, re.M) else name
        tags = [t.strip().lower() for t in m.get('tags', '').split(',') if t.strip()]
        status = m.get('status', '')
        areas = sorted({AREA[t] for t in tags if AREA.get(t)})
        versions = [t for t in tags if VERSION.match(t)]
        st = status.lower()
        shipped = st.startswith(('implemented', 'partially'))
        gone = 'deprecated' in tags or st.startswith('deprecat')
        flags = []
        # ★ = shipped server behaviour an operator can observe — the internals layer, read these first
        if 'server' in tags and shipped and not gone:
            flags.append('★')
        for word, flag in (('implemented', 'implemented'), ('partially', 'partial'),
                           ('approved', 'approved'), ('proposed', 'proposed'), ('deprecat', 'deprecated')):
            if st.startswith(word):
                flags.append(flag)
        if gone and 'deprecated' not in flags:
            flags.append('deprecated')
        if 'refinement' in tags:
            flags.append('refinement')
        flags += versions
        rows.append({'n': int(num.group(1)), 'file': name, 'title': title, 'status': status,
                     'date': m.get('date', ''), 'author': m.get('author', ''),
                     'area': ' '.join(areas), 'tags': ', '.join(tags), 'flags': ' '.join(flags),
                     'summary': keep.get(num.group(1), '')})
    rows.sort(key=lambda r: r['n'])
    n_star = sum(1 for r in rows if '★' in r['flags'])
    head = f"""# ADRs — nats-architecture-and-design

One row per ADR in `raw/adr/`, generated by `tools/triage-adrs.py` (re-run it after adding ADRs;
it preserves the `summary` column). {len(rows)} ADRs, {n_star} flagged ★ — those describe
server-side behaviour an operator can observe and are the internals layer of this wiki.

Ingest a row by writing `wiki/summaries/s-adr-<n>-<slug>.md` and putting the link in the last
column. `status` and `tags` are the ADR's own metadata, `area` is this wiki's facet.

| # | file | title | status | area | tags | flags | summary |
|---|---|---|---|---|---|---|---|
"""
    body = ''.join(f"| {r['n']} | {r['file']} | {r['title']} | {r['status']} | {r['area']} | "
                   f"{r['tags']} | {r['flags']} | {r['summary']} |\n" for r in rows)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(head + body)
    print(f'wrote {OUT}: {len(rows)} rows, {n_star} ★')
    print('status:', dict(collections.Counter(r['status'] for r in rows)))


if __name__ == '__main__':
    main()
